# Generated by Django 4.2.11 on 2024-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(upload_to='tags/icons/')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
