# Generated by Django 4.2.11 on 2025-01-08 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorios', '0002_alter_laboratorio_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_num', models.CharField(max_length=3)),
                ('situacao', models.CharField(choices=[('em uso', 'Em Uso'), ('disponivel', 'Disponível'), ('atrasada', 'Atrasada')], default='disponivel', max_length=10)),
                ('campus', models.CharField(default=None, max_length=4, null=True)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chave', to='laboratorios.laboratorio')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Pegar_Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(default='usando', max_length=20)),
                ('pegada_em', models.DateTimeField(auto_now_add=True)),
                ('tempo_max_devolucao', models.DateTimeField()),
                ('campus', models.CharField(default=None, max_length=4, null=True)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chave_pegada', to='pegar_chave.chave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chave_pegada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pegada_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='chave',
            constraint=models.UniqueConstraint(fields=('bloco_num', 'campus'), name='nome da chave de sala comum único no Campus.'),
        ),
    ]
